New folder/task/Areas/admin/Controllers/BlogCategoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Task22_12_2021.Data;
using Task22_12_2021.Models;

namespace Task22_12_2021.Areas.admin.Controllers
{
    [Area("admin")]
    public class BlogCategoryController : Controller
    {
        private readonly AppDbContext _context;

        public BlogCategoryController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Categories.ToList());
        }


        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(Category model)
        {
            _context.Categories.Add(model);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        



        public IActionResult Update(int id)
        {
            return View(_context.Categories.Find(id));
        }

        [HttpPost]
        public IActionResult Update(Category model)
        {
            _context.Categories.Update(model);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            Category category = _context.Categories.Find(id);

            bool IsRelation = _context.Blogs.Any(c => c.CategoryID == category.ID);

            _context.Categories.Remove(category);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

New folder/task/Areas/admin/Views/BlogCategory/Create.cshtml
@model Category
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <form asp-area="admin" asp-controller="blogCategory" asp-action="create" method="post">
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label">Name</label>
                    <input class="form-control" asp-for="@Model.Name">
                </div>
                <button type="submit" class="btn btn-primary"><i class="fas fa-plus"></i></button>
            </form>
        </div>
    </div>
</div>

New folder/task/Areas/admin/Views/BlogCategory/Index.cshtml
@model List<Category>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12 my-5">
            <a asp-area="admin" asp-controller="BlogCategory" asp-action="Create" class="btn btn-primary"><i class="fas fa-plus"></i></a>
        </div>
        <hr />
        <div class="col-lg-12 d-flex  justify-content-center">
            <table class="table w-75">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Category</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    @{int i = 0; }
                    @foreach (var item in Model)
                    {
                        i++;
                        <tr>
                            <th scope="row">@i</th>
                            <td>@item.Name</td>
                            <td>
                                <a asp-area="admin" asp-controller="blogCategory" asp-action="update" asp-route-id="@item.ID" class="btn btn-success"><i class="far fa-edit"></i></a>
                                <a asp-area="admin" asp-controller="blogCategory" asp-action="delete" asp-route-id="@item.ID" class="btn btn-danger"><i class="far fa-trash-alt"></i></a>
                            </td>
                        </tr>
                    }

                </tbody>  
            </table>
        </div>
    </div>
</div>

New folder/task/Areas/admin/Views/BlogCategory/Update.cshtml
@model Category
@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <form asp-area="admin" asp-controller="blogCategory" asp-action="update" method="post">
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label">Name</label>
                    <input class="form-control" asp-for="@Model.Name">
                </div>
                <input asp-for="@Model.ID" hidden />
                <button type="submit" class="btn btn-primary"><i class="far fa-edit"></i></button>
            </form>
        </div>
    </div>
</div>